# The objects of the Symbol class represent the names present inside the Ruby interpreter. They are usually generated by using :name literal syntax or by using to_sym methods.
# Symbol objects

# context 3
module Geeks1
  class Max
  end
  $a1 = :Max
end

# context 1
module Geeks2
  Max = 1
  $a2 = :Max
end

# context 2
def Max()
end

$a3 = :Max

puts $a1.object_id
puts $a2.object_id 
puts $a3.object_id

# all_symbols : This method returns an array of symbols that currently present in the Ruby's symbol table.
puts Symbol.all_symbols.size 
puts Symbol.all_symbols[1, 20]

# id2name : This method returns a string that is representation of sym.
p :Geeks.id2name
p :"Welcome to GeeksforGeeks Portal".id2name

# inspect : This method return the representation of sym in the form of symbol literal
p :geeks.inspect
p :"welcome to geeksforgeeks portal".inspect

# to_s : This method is similar to Symbol#id2name. This method returns the name or a string that corresponding to sym.
p :geeks.to_s
p :"welcome to geeksforgeeks portal".to_s

# <=> :It compares sym to other_sym after calling to_s. It returns -1 if sym is less than other_sym, it returns 0 if sym is equal to other_sym, or it returns +1 if sym is greater than other_sym.
a= :geeks
b = :"welcome to geeksforgeeks portal"
puts a<=>b # -1
c= :geeks
puts a<=>c # 0
puts b<=>a # 1

# == : It returns true if the sym is equal to obj, otherwise it return false.
a= :geeks
b = :"welcome to geeksforgeeks portal"
puts a==b # false
c= :geeks
puts a==c # true

# [] : This method returns the value of sym.to_s[].
# :name[]              # => "name"
# :name[2..4]          # => "me"  
# :name[/[aeiou]/, 1]  # => "a"
# :name["na"]          # => "na"
# :name["xyz"]         # => nil

# Practical use - extract from keys
hash = {name: "John", age: 30}
p hash.keys.find { |k| k[/name/] }  # => :name

params = {user_name: "John", user_email: "john@example.com"}
user_keys = params.keys.select { |k| k[/user_/] }  # => [:user_name, :user_email]
puts user_keys[0]  # => :user_name
puts user_keys[0]["name"]

version_sym = :user_v2_3_profile
match = version_sym[/v(\d+)_(\d+)/, 1]  # Captures first group "2"
puts match  # => "2"

# capitalize : This method is similar to Symbol#to_s
p :geeks.capitalize # :Geeks

# casecmp : This method is case-insensitive version of symbol <=$gt;. It will return -1, 0, 1, or nil. It is worked on A-Z/a-z, not on all Unicode. In this method nil is returned when the two symbols have incompatible encodings or if other_sym is not a symbol.
puts :GeeKs.casecmp(:geeks) # 0
puts :GeeKsGfg.casecmp(:geeksG) # 1
puts :GeeKsGfg.casecmp(:geeksGfgz) # -1
puts :GeeKsGfg.casecmp(3) # nil

# downcase : This method converts upper-case letters in lower-case.
puts :"WELCOME TO GEEKSFORGEEKS".downcase # welcome to geeksforgeeks

# length : This method returns the length of the given sym
puts :GeeKsGfg.length # 8

# slice : This method is similar to Symbol#to_s. This method provides you character on the given index from the sym 
p :GeeKsGfg.slice(3) # K
p :GeeKsGfg.slice(6) # f

# swapcase : This method interchange the case of the characters that present in sym. In other words, it converts lower-case into upper-case and upper-case into lower-case.
p "WELcome TO geeksFORGEEKS".swapcase # "welCOME to GEEKSforgeeks"

# upcase : This method converts lower-case characters into upper-case
p "welcome to geeksforgeeks".upcase # WELCOME TO GEEKSFORGEEKS

# to_proc : This method return a Proc object which answer to the given method by sym.
p (1..5).collect(&:to_s)

# to_sym This method returns a symbol that corresponding to an object. Here sym has been already a symbol, so in this case it returns it.
sym = "hello"
result = sym.to_sym
puts result    # => :hello
puts result.class  # => Symbol
